### ISSUE TITLE
Cache error in python stemmer

### ISSUE THREAD

**Issue by jonathlela** [snowballstem/snowball#106]
When calling the `stemWords` method in python stemmer, it may crashes with the following error:

`AttributeError: 'FrenchStemmer' object has no attribute 'clear_cache'`

It must be an error in the code as the `_clear_cache` method exists and is called by the sister method `stemWord`.

I've made a PR to fix this issue:

https://github.com/snowballstem/snowball/pull/105

**Comment by ojwb** [comment]
Thanks, applied.
