### ISSUE TITLE
[rust] warning: trait objects without an explicit `dyn` are deprecated

### ISSUE THREAD

**Issue by ojwb** [snowballstem/snowball#111]
We're currently seeing a number of these warnings from CI here and below:

https://travis-ci.org/snowballstem/snowball/jobs/581014461#L342

The Rust compiler seems to be suggesting to just insert `dyn ` before in every instance, but I know pretty much nothing about Rust and have no idea if that's actually the appropriate fix.

@JDemler Please could you take a look?

Also is there an equivalent of GCC's `-Werror` which would cause new warnings to make CI fail so we can't miss them?  I only spotted this while cleaning up the CI config.

**Comment by JDemler** [comment]
Fixed and discussed in #112 .

**Comment by ojwb** [comment]
Thanks, #112 merged and a patch file to revert the change added for anyone still using Rust < 1.27.
