### ISSUE TITLE
release a python wheel

### ISSUE THREAD

**Issue by graingert** [snowballstem/snowball#115]

**Comment by mitya57** [comment]
A wheel is now available here: <https://pypi.org/project/snowballstemmer/#files>.

**Comment by mitya57** [comment]
@Mogost The wheel is built from the same commit as the tarball (6169ef2456afeab15d53748627c139d7d022149e).

**Comment by Mogost** [comment]
@mitya57 thank you

**Comment by graingert** [comment]
@mitya57 can you release a .post0 build with the new wheel?

**Comment by mitya57** [comment]
@graingert I think I will do 1.9.2 instead, a bit later.

**Comment by ojwb** [comment]
Changes merged, but actually uploading a wheel is needed.

> I think I will do 1.9.2 instead, a bit later.

FWIW, I'm attempting a push to actually get 2.0.0 out, though something urgent may crop up elsewhere needing my attention.

**Comment by graingert** [comment]
It would be useful to get .post versions with wheels of all the past
releases

**Comment by mitya57** [comment]
> It would be useful to get .post versions with wheels of all the past releases

Why would you need it?

**Comment by mitya57** [comment]
I have just uploaded 2.0.0 release with a wheel.

@ojwb Please close this issue.
