### ISSUE TITLE
Stemming algorithm for Faroese

### ISSUE THREAD

**Issue by brandurjacobsen** [snowballstem/snowball#124]
Hi, I would like to contribute a stemming algorithm for Faroese.
How do I get the required permissions to do a push?

Regards
Brandur

**Comment by ojwb** [comment]
> How do I get the required permissions to do a push?

The workflow is that you fork the repo to give you your own copy,
commit your changes and push them to your fork, then open a "pull
request" which gets automatically tested and manually reviewed before
merging.

See https://help.github.com/en/github/getting-started-with-github/fork-a-repo
for generic github help on this.

See also our `CONTRIBUTING.rst` file which describes what you need to
do to add a new stemming algorithm.

**Comment by brandurjacobsen** [comment]
Thank you for the speedy reply. A case of RTFM I now admit...
