### ISSUE TITLE
Ukrainian algorithm

### ISSUE THREAD

**Issue by tggo** [snowballstem/snowball#130]
found algorithm for Ukrainian lang in this repo
https://github.com/Tapkomet/UAStemming

It would be great if you added it

**Comment by ojwb** [comment]
Please see https://github.com/snowballstem/snowball/blob/master/CONTRIBUTING.rst#adding-a-new-stemming-algorithm for the process for adding a new algorithm.

**Comment by ojwb** [comment]
Closing - see #178 for active work on this.
