### ISSUE TITLE
What is Stemming?

### ISSUE THREAD

**Issue by nutjob4life** [snowballstem/snowball#131]
I saw `snowballstemmer` being brought in as a dependency and was curious what such an unusually named package was. The [PyPI page](https://pypi.org/project/snowballstemmer/) doesn't mention *what stemming is* or why Snowball algorithms are noteworthy for it 🤷‍♀️

The GitHub repository's [README](https://github.com/snowballstem/snowball/blob/master/README) makes a mention to a site `snowballstem.org` which, frustratingly, also fails to say what stemming is. A Google search and a wikipedia entry later explains it 🤦‍♀️

Both the PyPI and the README ought to at least give a one line description of what stemming is, perhaps:

> Stemming is the process of finding word "stems" (bases or root forms) from derived or inflected forms, such as `fisher`, `fishing`, `fished` → `fish`

**Comment by ojwb** [comment]
Thanks for highlighting this.  It's all to easy to miss such a silly omission when you already know.

> such as fisher, fishing, fished → fish

`fisher` isn't actually stemmed to `fish` by our English stemmer, but `fishes` is so that would be a better example.

**Comment by ojwb** [comment]
I've now added text to the website front page and the README to explain the basics.

I don't know where the PyPI description comes from, as the text there doesn't seem to be present in the repo.

Hopefully @mitya57 can help there.

**Comment by mitya57** [comment]
The PyPI description will use https://github.com/snowballstem/snowball/blob/master/doc/libstemmer_python_README for the next release.

This was changed in dcfa46fe91c63f59, but that commit was not included in 2.0 release.

**Comment by ojwb** [comment]
@mitya57 Thanks, that clears up my confusion.

I've copied the "What is Stemming?" section there.  I'd rather not duplicate docs like this, but I think it's more important to actually address the valid complaint made here rather than block it on implementing a mechanism to avoid this duplication.
