### ISSUE TITLE
Pre-built Binaries

### ISSUE THREAD

**Issue by aviks** [snowballstem/snowball#133]
I just wanted to let you know that the Julia community provides pre-built binary artifacts for various native dependencies, and has recently built them for Snowball. These binaries, for many different architectures and operating systems, are available from https://github.com/JuliaBinaryWrappers/Snowball_jll.jl/releases . The bundles contain a shared library (`.dylib/.so/.dll`) and the `stemwords` executable. They were built from the Snowball C library download. They've been built for all available encodings. 

Background infromation about the cross-compiler based build system can be found at https://binarybuilder.org/

[Please close this issue when convenient-- it's only for your information]

**Comment by ojwb** [comment]
Thanks for letting us know.

However, I'm not comfortable with promoting binaries built by third parties via a link on the website.  Your intentions are likely good, but I just can't tell what's actually in a binary build short of rebuilding it myself and (assuming your builds are reproducible) checking I get a bit-for-bit identical result.  But I don't really have the time or energy to do that.
