### ISSUE TITLE
Incorrect UTF-8 extraction in the C runtime

### ISSUE THREAD

**Issue by stcarrez** [snowballstem/snowball#138]
While developping the Ada generator and reading the existing source base, I've found an error in the `get_utf8`
and `get_b_utf8`.

The UTF-8 extraction is incorrect for the 4-bytes encoding:

```
    *slot = (b0 & 0xE) << 18 | b1 << 12 | b2 << 6 | (p[c] & 0x3F);
```

The `0xE` is incorrect, and it should be `0x7` since we must keep only the 3 lower bits.

The impact is limited since it affects some subsets in the range U+40000 to U+FFFFF.

**Comment by ojwb** [comment]
Oh yes, well spotted.
