### ISSUE TITLE
How to go about product names like Kubernetes

### ISSUE THREAD

**Issue by SirWindfield** [snowballstem/snowball#145]
Hey!

I am really new to the whole NLP stuff and was wondering how I would go about product names that interfere with the stemming algorithms. For example `kubernetes` get stemmed (with the English stemmer) into `kubernet`. What approach can I take to keep names like these intact? The only idea I had was to use NER and only stem on non-named entities.

**Comment by ojwb** [comment]
You need to make sure you use the same stemming algorithm at both indexing and search time, and then it will just work - a document containing `Kubernetes` will be indexed by the term `kubernet` but a search for `kubernetes` will also stem to `kubernet` so will find that document.

More complex approaches are certainly possible, but I think you'd do better to email the list if you want to discuss such things - the list is read by many more people and from a more diverse range of backgrounds.
