### ISSUE TITLE
Question regarding redistribution

### ISSUE THREAD

**Issue by ClaudiuCeia** [snowballstem/snowball#168]
Hi Snowball authors,

Thanks for creating this awesome project! I wanted to write a stemmer in Typescript for the Romanian language when I stumbled upon [this](https://snowballstem.org/algorithms/romanian/stemmer.html) and I discovered Snowball. 

Needless to say, it made less and less sense to continue on my initial path and eventually I figured the best option would be to have a wrapper around the existing Snowball algorithms, so I published [this Typescript port](https://github.com/ClaudiuCeia/snowball-ts). 

When you get a chance, can you please let me know if I'm in violation of any terms or if there's any additional attribution I should be including? My own code is just a very thin layer on top of the compiled Javascript sources from Snowball.

**Comment by ojwb** [comment]
I don't see any problems from a quick look.

There's also an open PR to add Typescript support directly to Snowball (#155).  It seems to be in need of someone with more Typescript knowledge to finish it off, so maybe you'd be interested.
