### ISSUE TITLE
Greek Stemmer

### ISSUE THREAD

**Issue by vkovac2** [snowballstem/snowball#180]
Hello.

Is there a Greek Stemmer available? Here it says that there is one (https://github.com/snowballstem/snowball/blob/master/libstemmer/modules.txt), but I can't really find it.

Thanks

**Comment by ojwb** [comment]
Yes, https://github.com/snowballstem/snowball/blob/master/algorithms/greek.sbl

You can try it out online: https://snowballstem.org/demo.html#Greek
