### ISSUE TITLE
German stemmer mis-stems 'System'

### ISSUE THREAD

**Issue by srkunze** [snowballstem/snowball#19]
Systeme -> System
Systemen -> System
Systemes -> System
Systems -> System
but
System -> Syst

Please confer thread here as well: http://www.postgresql.org/message-id/55642C5B.60809@tbz-pariv.de

**Comment by srkunze** [comment]
The issue at hand here (at least from my perspective) is that snowball try to stem a stem (which is not necessarily a real German word).

Stems that are no real word should be left untouched.

**Comment by ojwb** [comment]
Snowball doesn't aim to make stemming an idempotent operation, only to map words which ought to be conflated to the same string and words which ought not be conflated to different strings.

> Stems that are no real word should be left untouched.

That's definitely not a design goal, so this isn't a bug.

**Comment by ojwb** [comment]
Actually there was a bug here - looks like I failed to check at the time but `System` itself is a German word and ideally should stem with the other forms (https://en.wiktionary.org/wiki/System#German).

#161 reported that part and we addressed it in 867c4ec70debd4daa7fb4d5a9f7759b47887d0b9 (which hasn't been in a release yet).
