### ISSUE TITLE
snowballstemmer Python package does not declare supported Python versions

### ISSUE THREAD

**Issue by andy-maier** [snowballstem/snowball#191]
The Python package for snowballstemmer defines the supported Python versions only as Trove classifiers (here: https://github.com/snowballstem/snowball/blob/master/python/setup.py#L48). That is not used by pip to find out whether the package can be installed on a particular Python version.

pip (and other installers) use the Python versions declared in the `python_requires` argument to `setup()`. If Python 2.x is still supposed to show up there, the syntax to match the currently specified Trove classifiers (except for Python 2.6) would be:
```
python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*'
```

I suggest to remove Python 2.6 at this point because it was EOL about 10 years ago, and people that still need Python 2.x for some reason all use 2.7 today. 2.7 is also EOL, but since it is the last 2.x version several projects still support it. See here for what the PSF supports: https://devguide.python.org/versions/

**Comment by andy-maier** [comment]
I created PR #192 to address this issue.

**Comment by ojwb** [comment]
Closing in favour of #192.
