### ISSUE TITLE
No rule to make target 'check_python_arabic'

### ISSUE THREAD

**Issue by amaccis** [snowballstem/snowball#196]
When I exec "make check_python" I get

`make[1]: *** No rule to make target 'check_python_arabic'.  Stop.
`

but as far as I got the makefile seems to have the rule

```
check_python: python
	$(MAKE) $(libstemmer_algorithms:%=check_python_%)

check_python_%: $(STEMMING_DATA_ABS)/%
```

so clearly I'm doing something stupid. 
Any hint?

**Comment by amaccis** [comment]
I was right and indeed it was something stupid.

```
STEMMING_DATA ?= ../snowball-data
STEMMING_DATA_ABS := $(abspath $(STEMMING_DATA))
```

the path of STEMMING_DATA was not the correct one.
I'm closing the issue.

**Comment by ojwb** [comment]
I think we could (and should) do better here - the current error message doesn't give any useful clue as to the actual problem, and we don't clearly document the expectation that snowball-data is checked out in a sibling directory (it's sort of alluded to in `CONTRIBUTING.rst` but that seems to be all).  This doesn't seem like stupidity on your part.
