### ISSUE TITLE
Migrate from older version

### ISSUE THREAD

**Issue by c-seeger** [snowballstem/snowball#199]
I try to fix an old go project that uses snowball as a dependency and has the following line of code

```
var c = env.ByteIndexForHop(-(2))
if int32(env.LimitBackward) > c || c > int32(env.Limit) {
› break lab2
}
env.Cursor = int(c)
```
with `env *snowballRuntime.Env` the function `env.ByteIndexForHop` seems not to exist anymore and is breaking the code. Whats the proper way to migrate this code?

**Comment by c-seeger** [comment]
Since I have no clue what i'm doing here, i found the following commit introduced the change and was not marked as a major version change:
https://github.com/snowballstem/snowball/commit/bb54ae9c9d1618439b6fb707c8a1c0b9364e74e9

If i understand it correctly the following change should work:

```
 if !env.Hop(-(2)) {
 › break lab2
 }
```

**Comment by c-seeger** [comment]
feel free to close the issue and leave it as some documentation in case if someone hits the same issue

**Comment by ojwb** [comment]
You should use the Go support code from the same snowball version you used to generate the Go stemmer sources.  The interface to the Go support code is essentially an internal implementation detail, hence no major version bump for changes to its interface.  If you do that you shouldn't need to mess around with manually adjusting the generated code (which is liable to be error prone).
