### ISSUE TITLE
Java class generation

### ISSUE THREAD

**Issue by dainiusjocas** [snowballstem/snowball#23]
I'm working on a stemmer for Lithuanian language. Stemmer is going to be used in Lucene based search engine, therefore I need to use the generated Java class. 

In my algorithm I'm using the length of the word and I believe this causes me a problem.

I've been following this [tutorial](http://snowball.tartarus.org/runtime/use.html). The resulting Java class works fine with the example program. But Java code does not compile for using in it Lucene with this problem:
```
[...] /src/main/java/org/tartarus/snowball/ext/LithuanianStemmer.java:[589,27] error: current has private access in SnowballProgram
```
I see that the code which was generated by snowball compiler tries to get length of the string in this way:
```
(current.length());
```

Unfortunatelly, the implementation of `SnowballProgram` class that is used by [Lucene](https://svn.apache.org/repos/asf/lucene/dev/trunk/lucene/analysis/common/src/java/org/tartarus/snowball/SnowballProgram.java) has defined `current` field in this way 
```
 // current string
    private char current[];
```

So, if I want to use the generated class in Lucene, I have to manually change the call for string length in this way:
```
getCurrent().length();
```

Am I facing a bug? Or this is the expected behaviour?

**Comment by rmuir** [comment]
I think its an issue with lucene where we are based on an older revision of snowball.

**Comment by dainiusjocas** [comment]
So, for now it is OK to manually fix the generated Java code?

**Comment by rmuir** [comment]
yeah, IMO its purely a lucene issue, we have just fallen behind with snowball generation. it currently involves an older revision of the snowball code to regenerate.
