### ISSUE TITLE
Consider rare accented forms with French stemmer

### ISSUE THREAD

**Issue by stonio** [snowballstem/snowball#41]
Web Page [French stemming algorithm](http://snowballstem.org/algorithms/french/stemmer.html) does not mention other rarely used letters with diacritics. For instance:
* Ÿ → [L'Haÿ-les-Roses](https://en.wikipedia.org/wiki/L%27Ha%C3%BF-les-Roses)
* Ü → [Capharnaüm](https://fr.wikipedia.org/wiki/Capharna%C3%BCm)

Are these rare [diacritics in French orthography](https://en.wikipedia.org/wiki/French_orthography#Diacritics) considered in [French stemming algorithm](http://snowballstem.org/algorithms/french/stemmer.html)?

**Comment by ojwb** [comment]
They aren't (see the code of the stemmer here: https://raw.githubusercontent.com/snowballstem/snowball/master/algorithms/french/stem_ISO_8859_1.sbl - there aren't amongst the accented letters in the `stringdef` list).

The wikipedia link you give suggests both are only commonly seen in proper nouns, so aren't really of relevance to a stemming algorithm.  The stemmer leaves `haÿ` and `capharnaüm` unaltered, so the current behaviour seems entirely appropriate to me (try for yourself at http://snowballstem.org/demo.html).
