### ISSUE TITLE
Compiler generates invalid code for ANSI C

### ISSUE THREAD

**Issue by ralfjunker** [snowballstem/snowball#53]
The Snowball compiler currently generates C code which intermingles variable declarations and code, which is incompatible with ANSI C.

The fix is to declare the variable at the start of the block. Here is a patch that accomplishes this>

```patch
 compiler/generator.c | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/compiler/generator.c b/compiler/generator.c
index 30643ca..29aeef3 100644
--- a/compiler/generator.c
+++ b/compiler/generator.c
@@ -890,11 +890,11 @@ static void generate_slicefrom(struct generator * g, struct node * p) {
 
 static void generate_setlimit(struct generator * g, struct node * p) {
     int keep_c;
-    writef(g, "~{~k~C", p);
-    keep_c = g->keep_count;
-    w(g, "~Mint mlimit");
+    w(g, "~{int mlimit");
+    keep_c = g->keep_count + 1;
     write_int(g, keep_c);
     w(g, ";~N");
+    writef(g, "~M~k~C", p);
     generate(g, p->left);
 
     w(g, "~Mmlimit");
```

I have visually checked the result for all generated C stemmer files and found just the intended changes. The new code compiles well as ANSI C and passes all my tests.

**Comment by ojwb** [comment]
Submitting patches as pull requests is much more helpful, as then they get tested by CI, and can be merged with a single click.

I'm not entirely happy with the `+ 1` adjustment to `keep_c` in this patch though.  I'll take a look and see if there's a cleaner way - it seems to be just a `(void)m;` causing the problem.

What's the C compiler you're using that doesn't support C99?

We should also have CI builds set the compiler to C90 mode if we're going to aim to generate C90 code.

**Comment by ralfjunker** [comment]
Thanks for looking into this!

> Submitting patches as pull requests is much more helpful, as then they get tested by CI, and can be merged with a single click.

My apologies. I know too little about the generator code to to submit an acceptable patch. What I called "patch" was just meant to help reproduce the problem more easily.

> I'm not entirely happy with the ``+ 1`` adjustment to keep_c in this patch though. I'll take a look and see if there's a cleaner way - it seems to be just a (void)m; causing the problem.

I agree that the  ``+1`` is awkward. But so is [silently incrementing ``g->keep_count``](https://github.com/snowballstem/snowball/blob/e87eced35ddb2fea94a497b4053e56b18344b034/compiler/generator.c#L173) as a result of writing ``~k`` in [``writef(g, "~{~k~C", p);``](https://github.com/snowballstem/snowball/blob/e87eced35ddb2fea94a497b4053e56b18344b034/compiler/generator.c#L894). The ``+1`` just anticipates this.

> What's the C compiler you're using that doesn't support C99?

Formerly Borland, now Embarcadero C++ Builder.

> We should also have CI builds set the compiler to C90 mode if we're going to aim to generate C90 code.

I would appreciate if C89 / C90 mode would be tested. Especially since this issue here seems to be the only incompatibility - at least the only one I detected.
