### ISSUE TITLE
Java builds and tests

### ISSUE THREAD

**Issue by oerd** [snowballstem/snowball#6]
Hi @rboulton ,

I would like the Java stemmers to also be included in travis-ci builds, ideally with stemming tests like it's C counterparts (see #5).

If it's alright with you, I'd like to work on this and submit a pull-request shortly.

oerd

**Comment by ojwb** [comment]
Yes, this would certainly be good to have.

`GNUmakefile` currently doesn't have any code to try to actually build the generated java code, so probably the best approach is to add rules there to compile the java code and test it against `snowball-data`, then make `.travis.yml` run those rules.

**Comment by ojwb** [comment]
@oerd Is this still something you're interested in working on?

**Comment by ojwb** [comment]
While testing a Java code generator tweak by hand, I discovered a number of latent issues, and quickly implemented a simple `check_java` target to aid fixing them.  I've committed this in 16f9cd4453fd4660db061316e56f8aad4a9163de, as it seems better than not having anything.

**Comment by oerd** [comment]
@ojwb sorry for the absence... work has me working on other things.
That said, I have to dig up some code I used to test the Java stemmers some months back. I'll merge them after your commit.

**Comment by oerd** [comment]
This might be a long shot, but the main reason for the Java build and tests was to later include some improvements in the Java stemmers that might be of interest.

**Comment by ojwb** [comment]
I can't really given a generic pre-approval, but my aim is to merge changes which are generally useful.  I'd suggest opening a separate PR once they're ready.

**Comment by oerd** [comment]
Yeah, this is what I had in mind... not you accepting whatever came in :smile:

**Comment by ojwb** [comment]
The CI build now runs the java tests I added (8691223c08d456a9f65f56e4c3d378b51854ee48).

@oerd You indicated you might have some better Java test code, and that I should assign this to you - I'm happy to leave it open, but if that code is lost for good, or doesn't add anything to what we now have, we might as well close this.

(Further Java improvements welcome too of course, but that's not really part of this ticket).

**Comment by ojwb** [comment]
BTW, it seems I can't actually assign to you (in github terms), only to myself or rboulton.

**Comment by ojwb** [comment]
I'm going to close this ticket - the original issue was addressed over a year ago (CI builds now run Java tests).

@oerd Better Java test code and/or improvements to the Java stemmers are certainly still of interest - please just open a PR for them if/when they're ready.
