### ISSUE TITLE
When generating Java from *.sbl, with current SnowballProgram and java sources, current.length is not accessible anymore.

### ISSUE THREAD

**Issue by GerritDeMeulder** [snowballstem/snowball#63]
When generating Java from *.sbl files , in combination with the current SnowballProgram java file (2016072500L), `current.length` is not accessible anymore, because `current` is now a private StringBuffer.

So things like "len" and "size" don't compile, should you change them to  `getCurrent().length()` ?
(see the part with "Thanks to Wolfram Esser for spotting this problem." in `SnowballProgram.Java`)

**Comment by ojwb** [comment]
The current code in git master (which last changed back in June) has:

```
    protected StringBuffer current;
```

And looking at the git history, it's never been `private`.

Also, `make check_java` passes for me, and that tests the arabic and tamil stemmers, both of which use `len`.

**Comment by GerritDeMeulder** [comment]
My bad, I already had the code from 2009 from the original site included in the project, and I overlooked that this variable and  some methods got switched from protected to private when updating from github.

NB : Maybe a minor thing , but am I overlooking something, or are the second calls of methods slice_to and assign_to (from line 337 - 362 ) duplicate / redundant code ? (I don't see a difference in the second call for both)
