### ISSUE TITLE
Take default Java class name from output filename

### ISSUE THREAD

**Issue by GerritDeMeulder** [snowballstem/snowball#64]
When generating Java from *.sbl, class name is empty.
Note : I use a windows command / batch file  from the algorithms folder.
example  : `snowball dutch\stem_ISO_8859_1.sbl -o dutchStemmer_ISO -j`

resulting file : `dutchStemmer_ISO.java`

generated class name should be `dutchStemmer_ISO` but is empty, I put [missing] to indicate where : 

> // This file was generated automatically by the Snowball to Java compiler
>// http://snowballstem.org/
>
>package org.tartarus.snowball.ext;
>
>import org.tartarus.snowball.Among;
>
>/**
> * This class was automatically generated by a Snowball to Java compiler
> * It implements the stemming algorithm defined by a snowball script.
> */
>
>public class [missing]  extends org.tartarus.snowball.SnowballProgram {
>...

Also at the end of this file the same problem arises:

>    public boolean equals( Object o ) {
>        return o instanceof [missing];
>   }
>
>    public int hashCode() {
>       return [missing].class.getName().hashCode();
>   }

**Comment by GerritDeMeulder** [comment]
After a review (and test) of [http://snowballstem.org/runtime/use.html](url), I can conclude when compiling to java  the `[-n C]` (Class Name) parameter should not be empty, then the class name is generated correctly.
Since public classes should be in same file-name - at least in Android - is this not ambiguous ?

**Comment by ojwb** [comment]
> ambiguous

I don't see how it's ambiguous.  Do you mean "redundant" (and that the classname could be taken from the filename)?

**Comment by GerritDeMeulder** [comment]
Thanks for your quick reply.
Yes, I had some trouble finding the right English word, and the parameter is indeed redundant,  so this probably fits better.  (as far as my knowledge of JLS goes, this is also the case for Java in general, and not just android)

**Comment by ojwb** [comment]
I'm not really a Java person, but it certainly seems common practice and may even be a requirement of the language.  Either way, it would be a sensible default when `-n` isn't specified (and a much better default than the empty string, which as you've noticed means we generate code which doesn't compile).
