### ISSUE TITLE
Problems with Russian letter Ё

### ISSUE THREAD

**Issue by emirotin** [snowballstem/snowball#65]
As http://snowballstem.org/algorithms/russian/stemmer.html properly mentions, Russian alphabet contains letter Ё [jo] which is quite often replaced with Е, especially in regular, non-academic texts.

So indeed the beast approach is to replace Ё -> Е when stemming.

Now if you check the existing demo http://snowballstem.org/demo.html you can see that it doesn't actually happen.

Let's take Russian word for "honey" — «мёд», and its form with different ending — «мёдом».
If you paste it along with its "normalized" form (with Е) you can see that the form with Ё is not properly stemmed:
![demo](https://monosnap.com/file/7POF56REeDsTEQP9ZkLyYFOijBDgX9.png)

Here's sample input so that you can run the tests yourself: "мёд мёдом мед медом".

This is a serious problem when searching through the corpus of natural texts. Even if you're purist (like me in this case) and type all your search terms with properly placed Ё you won't be able to match the original texts that are using Е.

**Comment by emirotin** [comment]
UPD: I think I've misinterpreted the meaning of "we assume it is mapped into е". This probably means the onus of normalizing Ё -> Е is on the consumer?
Would it make sense to do the normalization in the algorithm instead?

**Comment by ojwb** [comment]
I think it is assumed that this normalisation has been done already, but it'd be more helpful if the algorithm just handled this for you.

I''m not sure if we want to do a global replace on the input (as currently happens if you preprocess as assumed) or if it would be better to handle this in a more nuanced way (e.g. treat "ё" as a vowel and normalise it in output).  It really comes down to whether it's better or worse or doesn't matter that words with endings containing "ё" are handled as if they used "e", but I don't know much about the Russian language myself.

**Comment by emirotin** [comment]
>  It really comes down to whether it's better or worse or doesn't matter that words with endings containing "ё" are handled as if they used "e", but I don't know much about the Russian language myself.

The thing is in real world written texts ё is already often substituted for е, partially because how Russian qwerty keyboard was designed (ё is out of place and less convenient to type).
So you already have to assume this substitution as (maybe partially) done in the input and thus the only sane way is to apply it to the rest of input.

**Comment by data-man** [comment]
@emirotin 
Have you tried the code from this [article](https://habrahabr.ru/post/131265/)?
I think that this is the right approach.

**Comment by emirotin** [comment]
I haven’t, how is it different from this implementation?
Essentially what I needed was an easy way to use the stemmer from node.js
code where I cannot substitute the SQLite source.
I do have the working solution now that uses fts5 plugin encapsulating the
lib from this repo and normalizes ё - е before inserting and before
searching which is good enough for me.
Here I’m just arguing that this lib could handle the normalization itself

**Comment by data-man** [comment]
@emirotin 
Try to do so:
Add to _algorithms/russian/stem_KOI8_R.sbl_:

> stringdef e    hex 'C5'
> **stringdef yo   hex 'A3'**
> stringdef zh   hex 'D6'
> ...
> define v '{a}{e}**{yo}**{i}{o}{u}{y}{e`}{iu}{ia}'

Add to _algorithms/russian/stem_Unicode.sbl_:

> stringdef e    hex '435'
> **stringdef yo   hex '451'**
> stringdef zh   hex '436'
> ...
> define v '{a}{e}**{yo}**{i}{o}{u}{y}{e`}{iu}{ia}'

**Comment by emirotin** [comment]
Honestly I doubt it will do the trick because it will treat Е and Ё differently.

So if the original text has "мёдом", and the human-typed search string is "мед" (which as you know is a pretty common case for non-academic texts to substitute one for another), the two stemmed words will not match even if the stemmer properly stems the former to "мёд".

Just to repeat I'm not talking here about solving my immediate problem which I have already solved by doing the normalization myself, but rather about making the library more friendly to the new users and easier to use. In my case before I realized what was causing the problem I've been staring at irrelevant search results.

**Comment by data-man** [comment]
My results:

**From:**
мёдом
медом
селезёнка
ёкнет
клёво
ёмко 
Каменотёсы
утёсы
протёсты
счёту

**To:**
мёд
мед
селезёнк
ёкнет
клёв
ёмко 
Каменотёс
утёс
протёст
счёт

**Comment by emirotin** [comment]
I'm afraid you're not hearing me. Stemming works correctly but it won't help if the source and the search string contained е/ё typed differently because in that case the stemmed bases will be different.
So this discussion is irrelevant to the original problem I've raised.

**Comment by data-man** [comment]
>  Stemming works correctly

Stemming works **not** correctly!
Currently _мёдом_ stemmed as  _мёдом_

And I don't agree that normalization should be performed automatically. Your proposed changes will affect all users.

**Comment by data-man** [comment]
IMO, it would be best to add two more algorithms (for different encodings) and its, e.g., "RussianN".
So users will have a choice.

**Comment by ojwb** [comment]
Choice doesn't seem so useful here though, especially as it's already documented that the stemmer assumes `ё` has been normalised to `е` before the stemmer is called.

If we add a new name for the modified stemmer here, there's at least as strong an argument to do so for pretty much any change to any stemmer, which would just create a confusing mess of variant stemmers over time.

**Comment by ojwb** [comment]
Oh, the demo needs updating still (that's not entirely automated yet).  Reopening so that doesn't get forgotten.
