### ISSUE TITLE
Numbers with finnish stemmer

### ISSUE THREAD

**Issue by samiasmundi** [snowballstem/snowball#66]
When entering a number to finnish stemmer with 2 or more trailing zeroes, last zero is removed.

_Addition:_ This issue applies not only to zeroes but all numbers, eg. "555", "9999" etc.

## Steps to reproduce
1. Open demo at snowballstem.org: http://snowballstem.org/demo.html
2. Select Finnish stemming algorithm
3. Enter a text including a nuber with two or more trailing zeroes, eg. "testattiin 2000"

## Expected result
1. Output will be "testat 2000"

## Actual result
1. Output is "testat 200" (last zero is gone)

**Comment by ojwb** [comment]
It looks like the problematic line is in `tidy`:

```
        goto non-V1 [next] -> x  x delete // undouble consonant
```

The problem there is that `V1` is vowels, but `non-V1` includes digits as well as consonants, so this will undouble digits too.

Something like this would address that, and fixes your testcase:

```
--- a/algorithms/finnish/stem_ISO_8859_1.sbl
+++ b/algorithms/finnish/stem_ISO_8859_1.sbl
@@ -24,7 +24,7 @@ externals ( stem )
 integers ( p1 p2 )
 strings ( x )
 booleans ( ending_removed )
-groupings ( AEI V1 V2 particle_end )
+groupings ( AEI V1 V1D V2 particle_end )
 
 stringescapes {}
 
@@ -35,6 +35,7 @@ stringdef o"   hex 'F6'
 
 define AEI 'a{a"}ei'
 define V1 'aeiouy{a"}{o"}'
+define V1D V1 + '0123456789'
 define V2 'aeiou{a"}{o"}'
 define particle_end V1 + 'nt'
 
@@ -176,7 +177,7 @@ backwardmode (
             do ( ['j'] 'o' or 'u' delete )
             do ( ['o'] 'j' delete )
         )
-        goto non-V1 [next] -> x  x delete // undouble consonant
+        goto non-V1D [next] -> x  x delete // undouble consonant
     )
 )
 
```

An alternative would be to add a grouping with all the Finnish consonants.

I think we need to carefully review uses of `non` elsewhere (both in this and the other algorithms).  As a general feature, the the algorithms shouldn't be conflating different numbers, as that's unhelpful for their intended purpose.

**Comment by ojwb** [comment]
> An alternative would be to add a grouping with all the Finnish consonants.

I went with this approach.  As well as fixing truncation of numbers, it also tends to leave foreign words alone more.

> I think we need to carefully review uses of `non` elsewhere (both in this and the other algorithms). As a general feature, the algorithms shouldn't be conflating different numbers, as that's unhelpful for their intended purpose.

I've reviewed all uses of `non` in this algorithm, and I'll look through the others now.

I'll also add a generic test that feeds some numbers into the stemmer and checks they aren't changed, which should help avoid introducing such problems with new stemmers or with future changes.
