### ISSUE TITLE
Arabic Stemmer

### ISSUE THREAD

**Issue by maimayeg** [snowballstem/snowball#86]
I installed the Stemmer and tried to use it with Arabic, but that's what I got

raise KeyError("Stemming algorithm '%s' not found" % lang)

KeyError: "Stemming algorithm 'arabic' not found"

Am I missing some dependencies, if so could you please could you please clarify what do I need to make this stemming work?

**Comment by ojwb** [comment]
Are you using the pure-python generated stemmers from this repo, or PyStemmer (which wraps the generated C stemmers)?  Both contain the same error message you quote...

I can't see why this wouldn't work with the code here, and the CI is successfully testing Arabic stemming with Python.

PyStemmer currently defaults to using a rather old snapshot of the C stemmers from before the Arabic stemmer was added.

**Comment by ojwb** [comment]
No response from submitter in 2.5 months so closing.
