### ISSUE TITLE
I can give you PyPI namespace "snowballstemmer"

### ISSUE THREAD

**Issue by shibukawa** [snowballstem/snowball#93]
I noticed @mitya57 imported Python code generator from my code (#24).

If someone wants to use the following namespace, I will give the ownership of the PyPI namespace:

https://pypi.org/project/snowballstemmer/

Newer version should be generated from this repository instead of mine.

**Comment by mitya57** [comment]
Thanks for proposing this!

The Python code generator has changed quite a lot since it was originally imported, so it would indeed be nice to bring the PyPI package up to date.

@ojwb Long term it would be better if you were the owner of that namespace as you are the upstream maintainer. However, if you have no time or interest in updating the package, I can do it too.

**Comment by ojwb** [comment]
> Long term it would be better if you were the owner of that namespace as you are the upstream maintainer. However, if you have no time or interest in updating the package, I can do it too.

I don't really have the time to deal with pypi packages (or the interest either, as I'm not a heavy Python user).  I think it's better for somebody who has the time and is more motivated to take care of them.

(The same goes for PyStemmer which wraps the C stemmers, though for that I'd really like to see someone take on the upstream maintenance too.)

@mitya57 So please go ahead.

**Comment by mitya57** [comment]
OK. @shibukawa My login on PyPI is same as here, https://pypi.org/user/mitya57/. I am not going to do any active work on the PyPI package, but I can synchronize it with upstream code from time to time.

@ojwb The current version on PyPI has version 1.2.1. Do you have any preference of what versions I should use? If you ever plan to make upstream releases it would be nice to synchronize version numbers.

**Comment by ojwb** [comment]
> Do you have any preference of what versions I should use? If you ever plan to make upstream releases it would be nice to synchronize version numbers.

I am working (though admittedly painfully slowly of late) towards a "Snowball 2.0" and the manual already says "New in Snowball 2.0" for some new features.  I think I'm going to need to just reserve a few days for sitting down and sorting out (or deferring) the remaining issues.

I agree it seems sensible to keep versions in sync with PyStemmer, so I'd suggest something like 1.9.x for now, to reflect that it's both a significant step above 1.2.1 and almost 2.0.

**Comment by shibukawa** [comment]
<img width="1241" alt="Screen Shot 2019-06-24 at 17 39 46" src="https://user-images.githubusercontent.com/564612/60004224-29699180-96a7-11e9-88e9-abbb50077776.png">

@mitya57 I gave you owner role to you.

**Comment by ojwb** [comment]
Thanks everyone.

I believe this is resolved, so closing.  If not, please speak up.

**Comment by mitya57** [comment]
I have just released version 1.9.0 on PyPI:

https://pypi.org/project/snowballstemmer/
